language: php

dist: trusty

sudo: false

php:
    - 7.2
    - 7.3

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - APP_ENV=test
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"

install:
    - composer install --no-interaction --prefer-dist

script:
    - composer validate --strict
    - composer check-style
    - composer analyse
    - composer test
