setono_sylius_partner_ads_admin_program:
    resource: |
        alias: setono_sylius_partner_ads.program
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: setono_sylius_partner_ads_admin_program
    type: sylius.resource

setono_sylius_partner_ads_admin_conversion:
    resource: |
        alias: setono_sylius_partner_ads.conversion
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        grid: setono_sylius_partner_ads_admin_conversion
        only: ['index', 'delete']
    type: sylius.resource
